version: "3.9"
services:
  server:
    image: adenn-requests-server
    container_name: adenn-server-compose
    ports:
      - '8080:8080'
    depends_on:
      - database
      - queue
    build:
      context: .
      dockerfile: ./Dockerfile
  database:
    image: postgres:14-alpine
    container_name: postgres-compose-adenn
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=adenn_requests
    ports:
      - '5555:5432'
    volumes:
      - db:/var/lib/postgresql/data
  queue:
    container_name: rabbitmq-compose-adenn
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      # AMQP protocol port
      - '5556:5672'
      # Management UI
      - '5557:15672'

volumes:
  db:
    driver: local