openapi: 3.0.3
info:
  title: Auth
  description: Auth endpoints for Adenn Requests API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: ar.sid
security:
  - CookieAuth: [ ]
paths:
  /auth/plex/login-url:
    get:
      security: [ ]
      summary: Returns a login url for Plex OAuth flow
      responses:
        '200':
          description: Successfully created and returned a plex login url
          content:
            application/json:
              schema:
                type: object
                properties:
                  loginUrl:
                    type: string
                  pinId:
                    type: number
                required:
                  - loginUrl
                  - pinId
  /auth/plex/callback:
    get:
      security: [ ]
      summary: Callback for Plex OAuth flow
      parameters:
        - in: path
          name: pinId
          schema:
            type: integer
          required: true
          description: PinID for Plex OAuth Flow
      responses:
        '302':
          description: User was successfully authenticated and is being redirected back to the application root
        '400':
          description: PinID was missing or invalid
        '401':
          description: Plex authentication failed, or user does not have access to Plex server
        '408':
          description: Timed out waiting for response from Plex authentication
  /auth/logout:
    get:
      summary: Logs user out of their current session
      responses:
        '302':
          description: User was logged out and is being redirect to application root
  /auth/token:
    post:
      summary: Creates a new Bearer API token to be used for API access
      responses:
        '401':
          description: User is unauthorized to create token
        '201':
          description: Token created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token