###
GET {{host}}/auth/plex/login-url?forwardHost=http://localhost:8080
Content-Type: application/json

###
GET http://localhost:8080/health
Content-Type: application/json

###
GET {{host}}/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/auth/plex/callback?pinId=123
Content-Type: application/json
Authorization: Bearer {{token}}
