GET {{host}}/search/multi?searchTerm="The Shallows"
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/search/tv?searchTerm="Attack on Titan"
Accept: application/json
Authorization: Bearer {{token}}


###
GET {{host}}/search/movie?searchTerm="Attack on Titan"
Accept: application/json
Authorization: Bearer {{token}}