### Search Multi
https://api.themoviedb.org/3/search/multi?api_key={{tmdbApiKey}}&query="Attack on Titan"
Content-Type: application/json
Accept: application/json

### Search Movie
https://api.themoviedb.org/3/search/movie?api_key={{tmdbApiKey}}&query="Attack on Titan"
Content-Type: application/json
Accept: application/json

### Search TV
https://api.themoviedb.org/3/search/tv?api_key={{tmdbApiKey}}&query="Attack on Titan"
Content-Type: application/json
Accept: application/json
